# Generated by Django 5.2 on 2025-08-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_events', '0002_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'event_comment',
            },
        ),
    ]
