# Generated by Django 5.2 on 2025-08-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_events', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'db_table': 'event_like',
                'unique_together': {('event_id', 'employee_id')},
            },
        ),
    ]
