# Generated by Django 5.2 on 2025-08-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_events', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='birthday_employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
