# Generated by Django 5.2 on 2025-08-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_events', '0005_comment_birth_date_comment_birthday_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
