# Generated by Django 5.2 on 2025-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_events', '0006_remove_comment_birth_date_comment_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
