# Generated by Django 5.2 on 2025-08-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_events', '0007_comment_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='birthday_employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
