# Generated by Django 5.2 on 2025-08-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_events', '0008_like_birth_year_like_birthday_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('event_id__isnull', False)), fields=('event_id', 'employee_id'), name='unique_event_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('birth_year__isnull', False), ('birthday_employee_id__isnull', False)), fields=('birthday_employee_id', 'birth_year', 'employee_id'), name='unique_birthday_like'),
        ),
    ]
