# Generated by Django 5.2 on 2025-08-07 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_events', '0009_alter_like_unique_together_like_unique_event_like_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(verbose_name='Текст на русском')),
                ('text_kz', models.TextField(verbose_name='Мәтін қазақша')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Birthday Message',
                'verbose_name_plural': 'Birthday Messages',
                'db_table': 'birthday_message',
            },
        ),
        migrations.CreateModel(
            name='QuoteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField()),
                ('text_kz', models.TextField()),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.CreateModel(
            name='BirthdayMessageUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday_employee_id', models.IntegerField()),
                ('birth_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_events.birthdaymessage')),
            ],
            options={
                'verbose_name': 'Used Birthday Message',
                'verbose_name_plural': 'Used Birthday Messages',
                'db_table': 'birthday_message_used',
                'constraints': [models.UniqueConstraint(fields=('birthday_employee_id', 'birth_year'), name='unique_birthday_message_per_year')],
            },
        ),
        migrations.CreateModel(
            name='QuoteMessageUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('date_used', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_events.quotemessage')),
            ],
            options={
                'verbose_name': 'Used Quote Message',
                'verbose_name_plural': 'Used Quote Messages',
                'db_table': 'quote_message_used',
                'constraints': [models.UniqueConstraint(fields=('employee_id', 'date_used'), name='unique_quote_per_employee_per_day')],
            },
        ),
    ]
