# Generated by Django 5.2 on 2025-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_events', '0010_birthdaymessage_quotemessage_birthdaymessageused_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('academy_events', 'Academy Events'), ('news', 'News'), ('vacation', 'Vacation'), ('mission', 'Mission'), ('holiday', 'Holiday')], default='academy_events', max_length=20),
        ),
    ]
