# Generated by Django 5.2 on 2025-08-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_events', '0011_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_kz',
            field=models.TextField(default='check'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title_kz',
            field=models.CharField(default='check', max_length=255),
            preserve_default=False,
        ),
    ]
