"""
Django settings for smart_apa_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os





# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-r(-_&3ixft35^q)uxd8&c3z75ra2s7i-+!c51q5#=yu+4rr-3^'
SECRET_KEY = 'KS2xDU_p9mGYYPdDAT9atuwlcHSLGt5A5JgtX3-D8QWxC57slpBdQZt31JVcdITEs9XmlwAp2IiSnqFkxYdosw'

SIMPLE_JWT = {
    'SIGNING_KEY': 'KS2xDU_p9mGYYPdDAT9atuwlcHSLGt5A5JgtX3-D8QWxC57slpBdQZt31JVcdITEs9XmlwAp2IiSnqFkxYdosw',
    'ALGORITHM': 'HS256',
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['*']
#ALLOWED_HOSTS = ['smart.apa.kz', 'api-smart.apa.kz', '192.168.11.20', 'localhost', '127.0.0.1', '192.168.10.138', '192.168.10.243']
ALLOWED_HOSTS = ['devsmart.apa.kz', 'devapi-smart.apa.kz', 'mzhd.apa.kz', 'localhost', '127.0.0.1', '192.168.41.152', '192.168.10.138']

CSRF_TRUSTED_ORIGINS = [
    'https://devapi-smart.apa.kz',
]

# Application definition

INSTALLED_APPS = [
    'django_filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'smart_apa_api',
    'smart_events',
    'rest_framework',
	  'rest_framework_simplejwt',
    'corsheaders',
    'import_export'    
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',                                          
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://devsmart.apa.kz",
    "https://devapi-smart.apa.kz",
    "https://mzhd.apa.kz",
    "https://pm.apa.kz",
    "https://hr.apa.kz",
    "https://certificate.apa.kz",
    "https://www.apa.kz",
    "https://icademium.apa.kz",
    "https://admission.apa.kz",
    "https://case.apa.kz",
    "https://journal.apa.kz",
    "https://repository.apa.kz",
    "https://reg.apa.kz",
    "https://sdo.apa.kz",
    "https://alumni.apa.kz",
    "https://academyconference30.apa.kz",
    "http://academyconference.apa.kz",
    "http://hc.apa.kz",
]
#CORS_ALLOW_ALL_ORIGINS = True
ROOT_URLCONF = 'smart_apa_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smart_apa_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
		'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'smart_apa_project',
        'USER': 'psql_admin1',
        'PASSWORD': 'psql#admin1@pass',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#STATIC_URL = 'static/'
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
