# Generated by Django 5.2 on 2025-04-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('tech_secretary', 'Tech Secretary'), ('candidate', 'Candidate'), ('videointerview_expert', 'Videointerview Expert'), ('essay_expert', 'Essay Expert'), ('manager', 'Manager'), ('admin', 'Admin')], default='tech_secretary', max_length=50)),
            ],
            options={
                'verbose_name': 'Admission User Access Role',
                'verbose_name_plural': '4. Admission User Access Roles',
                'db_table': 'admission_user_role',
            },
        ),
        migrations.CreateModel(
            name='ByuropassUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('usercreatedoc', 'User Create Doc'), ('signdoc', 'Sign Doc'), ('signdoc_security', 'Sign Doc Security'), ('us_pos', 'Us Pos'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='usercreatedoc', max_length=20)),
            ],
            options={
                'verbose_name': 'Byuropass User Access Role',
                'verbose_name_plural': '2. Byuropass User Access Roles',
                'db_table': 'byuropass_user_role',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kz', models.CharField(max_length=100)),
                ('ru', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': '7.3. Employees Department Table',
            },
        ),
        migrations.CreateModel(
            name='IcademiumUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('graduate', 'Graduate'), ('viewer', 'Viewer'), ('tech_secretary', 'Tech Secretary'), ('teacher', 'Teacher'), ('admin', 'Admin')], default='student', max_length=50)),
            ],
            options={
                'verbose_name': 'Icademium User Access Role',
                'verbose_name_plural': '6. Icademium User Access Roles',
                'db_table': 'icademium_user_role',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kz', models.CharField(max_length=100)),
                ('ru', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': '7.5. Employees Position Table',
            },
        ),
        migrations.CreateModel(
            name='RegApaUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin')], default='admin', max_length=50)),
            ],
            options={
                'verbose_name': 'RegApa User Access Role',
                'verbose_name_plural': '3. RegApa User Access Roles',
                'db_table': 'regapa_user_role',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kz', models.CharField(max_length=200)),
                ('ru', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': '7.2. Employees Region Table',
            },
        ),
        migrations.CreateModel(
            name='RegtestingUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('pm_candidate', 'Pm Candidate'), ('hr_candidate', 'Hr Candidate'), ('mzd_candidate', 'Mzd Candidate'), ('pm_admin', 'Pm Admin'), ('hr_admin', 'Hr Admin'), ('mzd_admin', 'Mzd Admin')], default='pm_candidate', max_length=50)),
            ],
            options={
                'verbose_name': 'Regtesting User Access Role',
                'verbose_name_plural': '5. Regtesting User Access Roles',
                'db_table': 'regtesting_user_role',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kz', models.CharField(max_length=100)),
                ('ru', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': '7.4. Employees Sector Table',
            },
        ),
        migrations.CreateModel(
            name='SmartApaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('superadmin', 'Super Admin')], default='user', max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('last_ad_check', models.DateTimeField(blank=True, null=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('bad_pwd_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Smart Apa User',
                'verbose_name_plural': '1. Smart Apa Users',
                'db_table': 'smart_apa_user_role',
            },
        ),
        migrations.CreateModel(
            name='Subordination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kz', models.CharField(max_length=100)),
                ('ru', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Subordination',
                'verbose_name_plural': '7.1. Employees Subordination Table',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_surename', models.CharField(max_length=100)),
                ('user_patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.department')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.position')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.region')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.sector')),
                ('subordination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.subordination')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': '7. Employees Table',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='subordination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.subordination'),
        ),
    ]
