# Generated by Django 5.2 on 2025-05-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
