# Generated by Django 5.2 on 2025-05-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0002_sector_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
