# Generated by Django 5.2 on 2025-05-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0003_employee_user_email_employee_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
