# Generated by Django 5.2 on 2025-05-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0004_alter_sector_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kz', models.CharField(max_length=100)),
                ('ru', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Region Department',
                'verbose_name_plural': '8.2. Region Departments Table',
            },
        ),
        migrations.CreateModel(
            name='RegionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kz', models.CharField(max_length=100)),
                ('ru', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Region Positions',
                'verbose_name_plural': '8.3. Region Positions Table',
            },
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Regions', 'verbose_name_plural': '8.1. Regions Table'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='region',
        ),
        migrations.CreateModel(
            name='RegionEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_surename', models.CharField(max_length=100)),
                ('user_patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('user_image', models.CharField(blank=True, max_length=200, null=True)),
                ('user_email', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.regiondepartment')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.region')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.regionposition')),
            ],
            options={
                'verbose_name': 'Region Employee',
                'verbose_name_plural': '8. Region Employees Table',
            },
        ),
    ]
