# Generated by Django 5.2 on 2025-05-28 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0005_regiondepartment_regionposition_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regapauserrole',
            name='region',
            field=models.IntegerField(choices=[(1, 'AST'), (2, 'ALM'), (3, 'ShYM'), (4, 'AKM'), (5, 'AKT'), (6, 'ALO'), (7, 'ATR'), (8, 'SHKO'), (9, 'ZHM'), (10, 'BKO'), (11, 'KRG'), (12, 'KST'), (13, 'KZL'), (14, 'MNG'), (15, 'PVL'), (16, 'SKO'), (17, 'TRK'), (18, 'ABI'), (19, 'JTS'), (40, 'ULT')], default=0),
        ),
        migrations.AlterField(
            model_name='regapauserrole',
            name='role',
            field=models.IntegerField(choices=[(2, 'Admin'), (4, 'Fiz')], default=4),
        ),
        migrations.AlterField(
            model_name='regionemployee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.regiondepartment'),
        ),
    ]
