# Generated by Django 5.2 on 2025-07-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0006_regapauserrole_region_alter_regapauserrole_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartapauser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartapauser',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='regapauserrole',
            name='role',
            field=models.IntegerField(choices=[(2, 'Admin'), (4, 'Fiz'), (6, 'TIKAdmin')], default=4),
        ),
    ]
