# Generated by Django 5.2 on 2025-07-17 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0007_smartapauser_last_login_smartapauser_last_logout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_chief',
            field=models.BooleanField(default=False, verbose_name='Является начальником'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.sector'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subordination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_apa_api.subordination'),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='smart_apa_api_employee',
        ),
    ]
