# Generated by Django 5.2 on 2025-07-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0008_employee_birth_date_employee_is_chief_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_sector_head',
            field=models.BooleanField(default=False, verbose_name='Заведующий сектором'),
        ),
    ]
