# Generated by Django 5.2 on 2025-08-04 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0009_employee_is_sector_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
