# Generated by Django 5.2 on 2025-08-06 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0010_alter_employee_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subordination',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='subordination/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
