# Generated by Django 5.2 on 2025-08-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0011_subordination_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='region_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
