# Generated by Django 5.2 on 2025-08-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0012_employee_region_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
