# Generated by Django 5.2 on 2025-08-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0013_employee_iin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': '8.1. Regions Table'},
        ),
        migrations.AddField(
            model_name='region',
            name='city_kz',
            field=models.CharField(default='Не указано', max_length=200),
        ),
        migrations.AddField(
            model_name='region',
            name='city_ru',
            field=models.CharField(blank=True, default='Не указано', max_length=200, null=True),
        ),
    ]
