# Generated by Django 5.2 on 2025-08-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_apa_api', '0014_alter_region_options_region_city_kz_region_city_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartapauser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
